<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration</title>
</head>
<body>
<form action="../php/view/register.php" method="post">
    <label for="">Login</label>
    <input type="text" name="login" value="">
    <label for="">Email</label>
    <input type="email" name="email" value="">
    <label for="">Password</label>
    <input type="password" name="password" value="">
    <input type="submit" name="sub" value="Registration">
</form>
</body>
</html>