<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>

<?php if(isset($existLogin) && $existLogin) {?>
<h1> LOGIN alredy is used </h1>
<? } ?>

<?php if(isset($existEmail) && $existEmail) {?>
    <h1> EMAIL alredy is used </h1>
<? } ?>


<form action="/register" method="post">
    <label for="">Login</label><br>
    <input type="text" name="login" value=""><br>
    <label for="">Email</label><br>
    <input type="email" name="email" value=""><br>
    <label for="">Password</label><br>
    <input type="password" name="password" value=""><br>
    <input type="submit" value="Registration"><br>
</form>
</body>
</html>